stages:
  raw_dataset_creation:
    cmd: python src/data/get_data.py --config=params.yaml
    deps:
    - src/data/get_data.py
    - data/external/train.csv
    outs:
    - data/raw/train.csv
    - data/raw/test_week1.csv
    - data/raw/test_week2.csv 
  
  split_data:
    cmd: python src/data/split_data.py --config=params.yaml
    deps:
    - src/data/split_data.py
    - data/raw/train.csv
    outs:
    - data/processed/churn_train.csv
    - data/processed/churn_test.csv

  train_and_evaluate:
    cmd: python src/models/train_model.py --config=params.yaml
    deps:
    - data/processed/churn_train.csv
    - data/processed/churn_test.csv
    - src/models/train_model.py
    params:
    - random_forest.max_depth
    - random_forest.max_features
    # metrics:
    # - report/scores.json:
    #     cache: false
    # - report/params.json:
    #     cache: false
    
  log_production_model:
    cmd: python src/models/log_production_model.py --config=params.yaml
    deps:
    - src/models/log_production_model.py
    outs:
    - models/model.joblib

  
