external_data_config:
  external_data_csv: data/external/train.csv
  target: churn 
  split_ratio_train: 0.3
  split_ratio_test: 0.5
  raw_train: data/raw/train.csv
  raw_test_week1: data/raw/test_week1.csv
  raw_test_week2: data/raw/test_week2.csv

raw_data_config: 
  raw_data_csv: data/raw/train.csv
  train_data_csv: data/processed/churn_train.csv
  test_data_csv:  data/processed/churn_test.csv
  train_test_split_ratio: 0.2
  target: churn 
  
model_dir: models/model.joblib

random_forest: 
  max_depth: 2
  max_features: 2

mlflow_config:
  artifacts_dir: artifacts
  experiment_name: experiment_random_forest 
  run_name: mlops
  registered_model_name: random_forest_model
  remote_server_uri: http://localhost:1234

prediction_data_config:
  prediction_data_csv: data/prediction/prediction.csv
  


